org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:/Program Files/Java/jdk-21
org.gradle.parallel=true
# Mod properties
mod_version=1.1.11-1.21.1
maven_group=com.maximpolyakov
archives_name=QuickLink
enabled_platforms=neoforge
minecraft_version=1.21.1
architectury_api_version=13.0.8
fabric_loader_version=0.18.4
neoforge_version=21.1.219
mekanism_version=1.21.1-10.7.19.85
# Jade for MC 1.21.1 NeoForge (via Modrinth maven)
jade_version=15.9.3+neoforge
# WTHIT API for MC 1.21.1 NeoForge (via maven2.bai.lol)
wthit_version=12.10.2
