modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "quicklink"
version = "${version}"
displayName = "QuickLink"
authors = ""
description = '''
Wireless item, fluid, energy and chemical transfer via configurable colour-coded channels.
'''

[[dependencies.quicklink]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quicklink]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quicklink]]
modId = "mekanism"
mandatory = false
versionRange = "[10.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "quicklink.mixins.json"
