modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "quicklink"
version = "${version}"
displayName = "QuickLink"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.quicklink]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quicklink]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quicklink]]
modId = "mekanism"
type = "optional"
versionRange = "[10.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.quicklink]]
modId = "jade"
type = "optional"
versionRange = "[15,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.quicklink]]
modId = "wthit"
type = "optional"
versionRange = "[12,)"
ordering = "AFTER"
side = "BOTH"

